### ISSUE TITLE
Problem with Marginal DMR Signal/Audio Fixes

### ISSUE THREAD

**Issue by firefighter76** [lwvmobile/dsd-fme#183] opened 2023-12-28 16:14 UTC
I encountered a problem with audio output with the "-o pulse" switch.

I receive DMR Simplex and during the audio output I hear speech and at the same time a noise like a duck quacking.
The speech only takes place in one slot; once on slot 1 and then again on slot 2. The “duck” is played on the other slot at the same time. I tried this with the switch -V 1 or -V 2.

At the same time I save the amb file. Only the desired speech can be heard here.

Edit:
Sorry, amb saves different both slots. How can I ensure that only the voice is played/saved?  The slot with the voice is numbered with VC1, VC2... in the log.

**Comment by lwvmobile** [comment] 2023-12-28 19:23
Going to need a little bit more information to attempt to reproduce the issue. I've never observed this before, and couldn't get it to trigger in any of the samples I have.

Which version are you running? Windows/Linux/Other and which build date or git build version number? Any specific patched version or applied patches?

What command are you running to start up DSD-FME?

How are you feeding DSD-FME signal? Be as descriptive as possible.

Is this purely DMR Simplex, or is this DCDM? Or is this DMR BS? You mentioned the other slot is showing IDLE and also mention VC1, VC2... so that is behavior on DMR BS only.

If possible, use the option `-c capture.bin` when starting DSD-FME to make a capture and run while you are receiving some voice signal. Then close out and zip that file up and attach the zip file in your next response for analysis.

**Comment by firefighter76** [comment] 2023-12-28 20:26
I start DSD-FME on my Raspberry Pi with the Github version from 12/28/2023 without a patch with the following command:

 dsd-fme -i rtl:2:XXX.XXXXM:19:-2:12:70 -
 fs -d DRM/ |ffmpeg -f pulse -i 0 -c:a libmp3lame -b:a 64k -vn -f mp3 icecast://user:password@XXX.XXX.XXX.XXX/dsd.mp3

The inlvl is 34%.
According to the log file it is a DMR BS signal.  Furthermore, the following red message sometimes appears in the log file during the conversation: SLCO CRC ERR.

**Comment by lwvmobile** [comment] 2023-12-28 20:41
I wonder if its something to do with using it in conjunction with ffmpeg and icecast like that. I've never tried it myself, that snippet in the usage was from another user, but it looks like they are using the commands seperately, so no idea if chaining them together with a pipe is the correct way to do what you are doing.

Just to rule one thing out at a time, can you hook up a local monitor or listen to the audio directly from the Raspberry Pi, and just use this part of your startup:

`dsd-fme -i rtl:2:XXX.XXXXM:19:-2:12:70 -fs -d DRM/`

In the meantime, I'll try to test this out for myself with icecast and see if I can reproduce what you are experiencing.

**Comment by firefighter76** [comment] 2023-12-29 11:56
I have the same problem with VLC streaming.
Both slots are always played, even though only one slot has a human voice. The overlay noises appear to be control noises.

**Comment by lwvmobile** [comment] 2023-12-29 14:47
Well, you didn't say what command you use when 'streaming with VLC', or how you are doing that.

Anyways, you didn't seem to attempt to take my suggestion and just listen to the output locally with the dsd-fme command by itself to attempt to isolate the issue, nor did you supply a capture.bin file for analysis.

At this point, my only suggestion is to have two terminal windows open, and run the dsd-fme command in one, and the ffmpeg to icecast or whatever streaming stuff you want to do in the other. 

Terminal 1:
`dsd-fme -i rtl:2:XXX.XXXXM:19:-2:12:70 -fs -d DRM/`

Terminal 2 (using `pactl list short sources` to verify which source to use for -i):
`ffmpeg -f pulse -i 1 -c:a libmp3lame -ab 64k -f mp3 icecast://source:password@192.168.X.X:8000/dsd-fme`

or 

Terminal 2(the method I used since I don't have icecast setup):
`ffmpeg -f pulse -i 1 -c:a libmp3lame -ab 64k -f mp3 ffmpeg_test_1.mp3`

It also helps to be able to listen to the output of the raspberry pi directly from its own audio hardware, and not via 'streaming'. If you want to fix the issue, you have to isolate the exact cause of the issue. I think your problem is trying to chain the ffmpeg command in a pipe on top of dsd-fme. I attempted to do that locally and couldn't get ffmpeg to produce any audio at all, but it worked fine once I broke the commands apart into separate instances. Its also possible that you need to choose the correct output from `pactl list short sources` as the input for ffmpeg. 



> The overlay noises appear to be control noises.

You said it sounded like a 'duck' earlier, and now it sounds like control noises?

**Comment by firefighter76** [comment] 2023-12-29 16:18
The problem seems to be that dsd-fme plays both slots at the same time, even though only one slot has voice listening. dsd-fme saves both slots with the -D parameter.
In the appendix you can hear an audio sample from the slot on which there is no voice.

Unfortunately I haven't been able to record a capture.bin yet.

Your suggestion with two terminals has the same effect on me as with one terminal.
The command for VLC stream is:
```
dsd-fme -i rtl:2:XXX.XXXXM:19:-2 -fs |cvlc -I DUMMY -q --sout
'#transcode{acodec=mp3,channels=2,samplerate=48000}:std{access=http,mux=raw,dst=0.0.0.0:XXXX}' pulse://0 --demux=rawaud --rawaud- channels 2 --rawaud-samplerate 24000 --sout-keep
```
[DSD-FME-X1.wav.zip](https://github.com/lwvmobile/dsd-fme/files/13794846/DSD-FME-X1.wav.zip)

**Comment by lwvmobile** [comment] 2023-12-29 16:26
Going by that, I'd say its a decoding failure of some sort, bad signal or similar, but again, can't analyze it without a sample of your signal or the output of the console log. Is the signal inverted?

**Comment by firefighter76** [comment] 2023-12-29 16:39
The signal is not inverted. Attached is an excerpt from the log file.
[dsdfme_log.txt.zip](https://github.com/lwvmobile/dsd-fme/files/13794939/dsdfme_log.txt.zip)

**Comment by lwvmobile** [comment] 2023-12-29 16:57
Just  based off of what I'm seeing in the log, I'd say the signal is pretty iffy/marginal. Either that, or the signal fades in and out. Seems to be a lot of rouge VC1 spurts when it should be a IDLE data sync there that isn't detected while in the voice loop, usually those will get picked up as CACH/TACT or EMB QR failures and be rejected, but sometimes they don't. Maybe try adjusting your antenna setup or trying another system, and see if you have any better results.

```
09:26:34 Sync: +DMR  [SLOT1]  slot2  | Color Code=03 | VC1
[33m SLC_P_SYS_PARMS: Tiny; Net ID: 6; Site ID: 1.2; Comp CC: 1; SYS: 0029;[0m
09:26:34 Sync: +DMR   slot1  [SLOT2] | Color Code=03 | VC1 
09:26:34 Sync: +DMR  
Closing MBE out file 1.
[slot1]  slot2  | Color Code=03 | IDLE 
09:26:34 Sync: +DMR   slot1  [SLOT2] | Color Code=03 | VC2 
09:26:34 Sync: +DMR  [slot1]  slot2  | Color Code=03 | IDLE 
[33m SLC_P_SYS_PARMS: Tiny; Net ID: 6; Site ID: 1.2; Comp CC: 1; SYS: 0029;[0m
09:26:34 Sync: +DMR   slot1  [SLOT2] | Color Code=03 | VC3 
09:26:34 Sync: +DMR  [slot1]  slot2  | Color Code=03 | IDLE 
09:26:34 Sync: +DMR   slot1  [SLOT2] | Color Code=03 | VC4 
09:26:34 Sync: +DMR  [slot1]  slot2  | Color Code=03 | IDLE 
[33m SLC_P_SYS_PARMS: Tiny; Net ID: 6; Site ID: 1.2; Comp CC: 1; SYS: 0029;[0m
09:26:34 Sync: +DMR   slot1  [SLOT2] | Color Code=03 | VC5 
09:26:34 Sync: +DMR  [slot1]  slot2  | Color Code=03 | IDLE 
09:26:34 Sync: +DMR   slot1  [SLOT2] | Color Code=03 | VC6 
[31m SLOT 2 FLCO FEC ERR [0m[31m (FEC ERR)[0m
[31m SLOT 2 SB/RC (FEC ERR) E:4; I:99B224B1 D:56A; [0m 
09:26:34 Sync: +DMR  [SLOT1]  slot2  | Color Code=03 | VC1 
[33m SLC_P_SYS_PARMS: Tiny; Net ID: 6; Site ID: 1.2; Comp CC: 1; SYS: 0029;[0m
09:26:34 Sync: +DMR   slot1  [SLOT2] | Color Code=03 | VC1 
09:26:34 Sync: +DMR  
Closing MBE out file 1.
[slot1]  slot2  | Color Code=03 | IDLE 
09:26:34 Sync: +DMR   slot1  [SLOT2] | Color Code=03 | VC2 
09:26:34 Sync: +DMR  [slot1]  slot2  | Color Code=03 | IDLE 
[33m SLC_P_SYS_PARMS: Tiny; Net ID: 6; Site ID: 1.2; Comp CC: 1; SYS: 0029;[0m
09:26:34 Sync: +DMR   slot1  [SLOT2] | Color Code=03 | VC3 
09:26:34 Sync: +DMR  [slot1]  slot2  | Color Code=03 | IDLE 
09:26:34 Sync: +DMR   slot1  [SLOT2] | Color Code=03 | VC4 
09:26:34 Sync: +DMR  [slot1]  slot2  | Color Code=03 | IDLE 
[33m SLC_P_SYS_PARMS: Tiny; Net ID: 6; Site ID: 1.2; Comp CC: 1; SYS: 0029;[0m
09:26:34 Sync: +DMR   slot1  [SLOT2] | Color Code=03 | VC5 
09:26:34 Sync: +DMR  [slot1]  slot2  | Color Code=03 | IDLE 
09:26:34 Sync: +DMR   slot1  [SLOT2] | Color Code=03 | VC6 
[31m SLOT 2 FLCO FEC ERR [0m[31m (FEC ERR)[0m
[31m SLOT 2 SB/RC (FEC ERR) E:4; I:99B224B1 D:56A; [0m 
09:26:34 Sync: +DMR  [SLOT1]  slot2  | Color Code=03 | VC1 
[33m SLC_P_SYS_PARMS: Tiny; Net ID: 6; Site ID: 1.2; Comp CC: 1; SYS: 0029;[0m
09:26:34 Sync: +DMR   slot1  [SLOT2] | Color Code=03 | VC1 
09:26:34 Sync: +DMR  
Closing MBE out file 1.
```

BTW, that appears to be the traffic channel on a Tier 3 system, You could trunk track that (if you don't already) if you knew the control channel frequency and the channel to frequency assignments on it.

**Comment by firefighter76** [comment] 2023-12-29 17:13
I've already thought something similar. The problem probably only occurs with simplex operation.

Would it make sense to use a 12-bit SDR stick?

Would it be possible to switch off the slot without a voice if a voice was previously heard on the other slot? Possibly switchable via another DSD-FME parameter?

> BTW, that appears to be the traffic channel on a Tier 3 system, You could trunk track that (if you don't already) if you knew the control channel frequency and the channel to frequency assignments on it.


The channel I'm listening to transmits in the upper band and the remote station in the lower band.

**Comment by lwvmobile** [comment] 2023-12-29 17:31
One thing you might be able to do is open GQRX on your Raspberry Pi and take a look at the signal in there and see if it looks faint, if it fades in and out, if another channel nearby is interfering, or maybe if its too powerful. It can definitely help you make adjustments and also verify PPM, gain values, etc. Its rare, but sometimes the signal can be way too strong and you need to back the gain down significantly if the repeater is in close proximity to your location. 

I've also found that some people will attempt to capture samples with their radio in simplex mode and be right next to their SDR or antenna and the signal is just trash due to the front end of the SDR being blown out by the radio due to its very close proximity. Same for repeater systems, their radio will overpower the front end of the dongle and when they are on their repeater, it makes the signal go from good to bad for the duration they are on their radio.

> Would it make sense to use a 12-bit SDR stick?

I honestly have no idea, I'm not an expert on the different dongles, but keep in mind that DSD-FME only supports the RTL based ones, since that's all I have, and also its easy enough just to use GQRX or SDR++ if I need to use a different device and feed the signal into DSD-FME that way instead. Speaking of which, if you are having some issues with rtl input directly, I've found that using SDR++ or GQRX with the correct parameters can help clean up signal (within reason).

**Comment by firefighter76** [comment] 2023-12-29 17:45
First of all thank you.

I will try to improve the reception with your tips.

**Comment by lwvmobile** [comment] 2023-12-29 19:43
Well, if it doesn't quite work out for you, I might can craft a patch for DMR BS to do a few additional checks to prevent those random VC1 spurts when it should be IDLE or DATA caused by random jitter or signal drop or whatever condition is causing that. Probably wouldn't be the best patch in the world, but good enough for this instance anyways.

**Comment by firefighter76** [comment] 2023-12-29 20:43
Unfortunately it still doesn't quite work.  The inLevel remains at ~35%.  Whatever, I do. 
I would be happy about a possible patch.

**Comment by lwvmobile** [comment] 2023-12-29 22:10
Alright, well I spent a little time making a few tweaks and crafted a quick patch, hopefully it'll help your particular situation. The patch does two things. 

First, in DMR BS decoding, it does a few additional checks for if a frame should be a voice frame vs if it should be a data frame, and if it thinks it should be a data frame, but doesn't receive a data sync pattern, it'll just skip that frame instead of trying to play it as voice and then continues with the other tdma frame.

Second, I have also reinstated the 'DMR Mono' mode, which was an old mode I used to force DMR BS voice sync into the DMR MS simplex handler. The downside to using it is that it discards the other TDMA slot when voice sync occurs, and just plays voice from a fixed single slot that is always designated as slot 1. The upside is, is that in situations like yours, it can actually help to stabilize marginal signal.

To use DMR Stereo, use the `-fs` switch to always decode both slots of DMR.

To use DMR Mono, use the `-fr` switch to decode both slots until voice sync occurs, then it goes to only decoding the voice in that slot (forced to slot 1), and discarding the opposite timeslot.

To apply this patch, open your dsd-fme folder in a terminal and run the commands:

```
git pull
git apply patch/FF76_DMR_BS_Tweaks_and_DMR_MONO_MODE.patch
git apply patch/wolf_tdma_mono_stereo.patch
cd build
sudo rm -rf *
cmake ..
make
sudo make install

```

You may want to extract the zip file outside of the dsd-fme folder, and then copy the .patch file into the patch folder first, otherwise git may complain if you perform a `git pull` to get up to the latest release version because it might think that zip file is a change. Optionally, you can apply that wolf patch as well, that has another requested change to have 1 voice play from both speakers at the same time, as opposed to the left channel for slot 1 and right channel for slot 2. If you use the `-fr` DMR Mono switch, you might as well use that patch as well, and even if you don't, I can understand the appeal of having the voice in both speakers while only one voice is present.

Anyways, just let me know if this helps out any. I haven't been able to thoroughly test this patch, but I think it'll work out okay in your particular situation.

[FF76_DMR_BS_Tweaks_and_DMR_MONO_MODE.zip](https://github.com/lwvmobile/dsd-fme/files/13796307/FF76_DMR_BS_Tweaks_and_DMR_MONO_MODE.zip)

**Comment by firefighter76** [comment] 2023-12-30 18:47
Thank you for the patch related to my problem.  I tested it with DMR stereo and the annoying noise on the non-voice slot is no longer audible.  Slot 1 can be heard on the left audio channel and slot 2 on the right audio channel (only the voice of course).
I haven't tested the second patch mentioned (to hear the voice in stereo) yet.
I have another question about DMR mono: Is only the received voice slot 1 played or also only the voice slot 2 received at a different time (is this routed to slot 1 by DSD-FME?)?

**Comment by lwvmobile** [comment] 2023-12-30 19:34
> I have another question about DMR mono: Is only the received voice slot 1 played or also only the voice slot 2 received at a different time (is this routed to slot 1 by DSD-FME?)?

It will receive both slots, but if there is a voice sync, it will only handle that slot with voice sync. All voice is forced through slot 1 in code, which is primarily use the stabilize DMR Simplex since its using the MS handling for DMR Voice, discarding the other time slot, which on Simplex, would just be dead air anyways.

**Comment by firefighter76** [comment] 2024-01-02 19:36
I also carried out the test with DMR Mono and found that the signal can be heard without any background noise.  Just like with the special patch from DMR Stereo.

If voices are recognized on both slots, both are played with DMR stereo split to L and R, and with mono only the slot on which voices were first recognized, or have I misunderstood that?

Now to the network.
The master channel (upper band frequency) is open as long as both interlocutur are communicating.  And the other interlocutor only transmits on the sub-band frequency when it speaks.

I also tested the trunking mode, but unfortunately the sync is not recognized.

**Comment by lwvmobile** [comment] 2024-01-02 20:52
> I also tested the trunking mode, but unfortunately the sync is not recognized.

Just no signal to sync on, or was it synchronizing? If it was synchronizing, but nothing but `CSBK (CRC ERR)` then it could be RAS enabled system, which you can bypass the RAS by just using the `-F` option, but I only recommend doing so if it really is a RAS system with good signal, otherwise, it may be lead to a lot of bad decodes and cause a lot of issues.

> interlocutur

That is the first time I have ever heard that word, and I had to look it up. I should have known though, has the same latin base as 'Locutus'.

**Comment by firefighter76** [comment] 2024-01-02 21:52
> Just no signal to sync on, or was it synchronizing? 

There is no signal to synchronize, although there should be a temporary signal. DSD-FME switch all the time between the frequencies in channel.csv.
Here is my channel.csv:

```
ChannelNumber(dec),frequency(Hz) (do not delete this line or won't import proper>
999,XXXXXXXXX
1,XXXXXXXXX
```

> That is the first time I have ever heard that word, and I had to look it up. I should have known though, has the same latin base as 'Locutus'.

Sorry, Google translate helped me.

**Comment by lwvmobile** [comment] 2024-01-03 00:01
If there is a t3 control channel, it should be on all the time, and not a temporary on/off signal. If you, you should see messages like this on it constantly. 

```
12:51:31 Sync: +DMR   slot1  [slot2] | Color Code=00 | IDLE 
 SLC_C_SYS_PARMS: Huge; Net ID: 2; Site ID: 1.54; Reg Req: 1; CSC: 216; SYS: 3435;
12:51:31 Sync: +DMR  [slot1]  slot2  | Color Code=00 | CSBK
 Announcements (C_BCAST) Specify Call Timer Parameters (CallTimer_Parms)
 Timers - Emergency: 511; Packet: 31; MS-MS: 511; Line: 511; 
12:51:32 Sync: +DMR   slot1  [slot2] | Color Code=00 | IDLE 
12:51:32 Sync: +DMR  [slot1]  slot2  | Color Code=00 | CSBK
 C_ALOHA_SYS_PARMS: Huge; Net ID: 2; Site ID: 1.54; Cat: A; SYS: 3435;
12:51:32 Sync: +DMR   slot1  [slot2] | Color Code=00 | IDLE 
 SLC_C_SYS_PARMS: Huge; Net ID: 2; Site ID: 1.54; Reg Req: 1; CSC: 217; SYS: 3435;
12:51:32 Sync: +DMR  [slot1]  slot2  | Color Code=00 | CSBK
 C_ALOHA_SYS_PARMS: Huge; Net ID: 2; Site ID: 1.54; Cat: A; SYS: 3435;
12:51:32 Sync: +DMR   slot1  [slot2] | Color Code=00 | IDLE 
12:51:32 Sync: +DMR  [slot1]  slot2  | Color Code=00 | CSBK
 C_AHOY - Private FID: 58 SVC: 00 UDT Short Data Polling Service Target: 1083519; Source: 16776946; 
12:51:32 Sync: +DMR   slot1  [slot2] | Color Code=00 | IDLE 

```

Or, if its a Motorola Capacity Max system, then you may see messages like this, noting that both slots are CSBKs all the time:

```
12:55:44 Sync: +DMR  [slot1]  slot2  | Color Code=04 | CSBK
 Announcements (C_BCAST) Adjacent Site Information (Adjacent_Site)
 Huge; Net ID: 1; Site ID: 4; SYS: 3404; Online; CC Pri: 0; AC Pri: 0; LPCN: 206;
12:55:44 Sync: +DMR   slot1  [slot2] | Color Code=04 | CSBK
 C_ALOHA_SYS_PARMS: Huge; Net ID: 1; Site ID: 1; SYS: 3401; Capacity Max
12:55:44 Sync: +DMR  [slot1]  slot2  | Color Code=04 | CSBK
 C_ALOHA_SYS_PARMS: Huge; Net ID: 1; Site ID: 1; SYS: 3401;
12:55:44 Sync: +DMR   slot1  [slot2] | Color Code=04 | CSBK
 C_ALOHA_SYS_PARMS: Huge; Net ID: 1; Site ID: 1; SYS: 3401; Capacity Max
 SLC_C_SYS_PARMS: Huge; Net ID: 1; Site ID: 1; Reg Req: 1; SYS: 3401;
12:55:44 Sync: +DMR  [slot1]  slot2  | Color Code=04 | CSBK
 Private Data Channel Grant: Single Item (PD_GRANT) - Logical
  LPCN: 0010; TS: 2; LPCN+TS: 0022; Target: 00100279 - Source: 00150841 
  Frequency: XXXXXX0 MHz
12:55:44 Sync: +DMR   slot1  [slot2] | Color Code=04 | CSBK
 C_ALOHA_SYS_PARMS: Huge; Net ID: 1; Site ID: 1; SYS: 3401; Capacity Max
12:55:44 Sync: +DMR  [slot1]  slot2  | Color Code=04 | CSBK
 Private Data Channel Grant: Single Item (PD_GRANT) - Logical
  LPCN: 0010; TS: 2; LPCN+TS: 0022; Target: 00100279 - Source: 00150841 
  Frequency: XXXXXXXXXXXX0 MHz
12:55:44 Sync: +DMR   slot1  [slot2] | Color Code=04 | CSBK
 C_ALOHA_SYS_PARMS: Huge; Net ID: 1; Site ID: 1; SYS: 3401; Capacity Max
 SLC_C_SYS_PARMS: Huge; Net ID: 1; Site ID: 1; Reg Req: 1; SYS: 3401;
12:55:44 Sync: +DMR  [slot1]  slot2  | Color Code=04 | CSBK
 C_ACKD Outbound TSCC; Response: 01; Reason: E0; Target: 150841; Source: 100279; 
12:55:44 Sync: +DMR   slot1  [slot2] | Color Code=04 | CSBK
 C_ALOHA_SYS_PARMS: Huge; Net ID: 1; Site ID: 1; SYS: 3401; Capacity Max
12:55:44 Sync: +DMR  [slot1]  slot2  | Color Code=04 | CSBK
 C_AHOY - Private FID: 00 SVC: 00 Packet Data Call Target: 150352; Source: 100279; 
12:55:44 Sync: +DMR   slot1  [slot2] | Color Code=04 | CSBK
 C_ALOHA_SYS_PARMS: Huge; Net ID: 1; Site ID: 1; SYS: 3401; Capacity Max
 SLC_C_SYS_PARMS: Huge; Net ID: 1; Site ID: 1; Reg Req: 1; SYS: 3401;
12:55:44 Sync: +DMR  [slot1]  slot2  | Color Code=04 | CSBK
 Announcements (C_BCAST) Adjacent Site Information (Adjacent_Site)
 Huge; Net ID: 1; Site ID: 3; SYS: 3403; Online; CC Pri: 0; AC Pri: 0; LPCN: 190;
12:55:44 Sync: +DMR   slot1  [slot2] | Color Code=04 | CSBK
 C_ALOHA_SYS_PARMS: Huge; Net ID: 1; Site ID: 1; SYS: 3401; Capacity Max
12:55:44 Sync: +DMR  [slot1]  slot2  | Color Code=04 | CSBK
 Talkgroup Voice Channel Grant (TV_GRANT) - Logical
  LPCN: 0010; TS: 1; LPCN+TS: 0021; Target: 01901000 - Source: 01901008 
  Frequency: XXXXXXX0 MHz

```

Finally, if its Capacity Max, and RAS protected, then you may see this on a control channel:

```
18:58:44 Sync: +DMR   slot1  [slot2] | Color Code=07 | CSBK (CRC ERR) 
18:58:44 Sync: +DMR  [slot1]  slot2  | Color Code=07 | CSBK (CRC ERR) 
18:58:44 Sync: +DMR   slot1  [slot2] | Color Code=07 | CSBK (CRC ERR) 
18:58:44 Sync: +DMR  [slot1]  slot2  | Color Code=07 | CSBK (CRC ERR) 
 SLC_C_SYS_PARMS: Small; Net ID: 2; Site ID: 1.4; Reg Req: 1; CSC: 0; SYS: 1023;
18:58:44 Sync: +DMR   slot1  [slot2] | Color Code=07 | CSBK (CRC ERR) 
18:58:44 Sync: +DMR  [slot1]  slot2  | Color Code=07 | CSBK (CRC ERR) 
18:58:44 Sync: +DMR   slot1  [slot2] | Color Code=07 | CSBK (CRC ERR) 
18:58:44 Sync: +DMR  [slot1]  slot2  | Color Code=07 | CSBK (CRC ERR) 
 SLC_C_SYS_PARMS: Small; Net ID: 2; Site ID: 1.4; Reg Req: 1; CSC: 0; SYS: 1023;
18:58:44 Sync: +DMR   slot1  [slot2] | Color Code=07 | CSBK (CRC ERR) 
18:58:44 Sync: +DMR  [slot1]  slot2  | Color Code=07 | CSBK (CRC ERR) 
18:58:44 Sync: +DMR   slot1  [slot2] | Color Code=07 | CSBK (CRC ERR) 
18:58:44 Sync: +DMR  [slot1]  slot2  | Color Code=07 | CSBK (CRC ERR) 
 SLC_C_SYS_PARMS: Small; Net ID: 2; Site ID: 1.4; Reg Req: 1; CSC: 0; SYS: 1023;
```

in which case, you'll want to use the `-F` switch to allow those CSBKs to be decoded and bypass the CRC errors

```
18:59:57 Sync: +DMR   slot1  [slot2] | Color Code=07 | CSBK
 C_ALOHA_SYS_PARMS: Small; Net ID: 1; Site ID: 3; SYS: 1023; Capacity Max -RAS 
18:59:57 Sync: +DMR  [slot1]  slot2  | Color Code=07 | CSBK
 C_ALOHA_SYS_PARMS: Small; Net ID: 1; Site ID: 3; SYS: 1023; -RAS 
18:59:57 Sync: +DMR   slot1  [slot2] | Color Code=07 | CSBK
 C_ALOHA_SYS_PARMS: Small; Net ID: 1; Site ID: 3; SYS: 1023; Capacity Max -RAS 
18:59:57 Sync: +DMR  [slot1]  slot2  | Color Code=07 | CSBK
 Announcements (C_BCAST) Adjacent Site Information (Adjacent_Site)
 Small; Net ID: 1; Site ID: 4; SYS: 1024; Online; CC Pri: 0; AC Pri: 0; LPCN: 12; -RAS 
 SLC_C_SYS_PARMS: Small; Net ID: 1; Site ID: 3; Reg Req: 1; SYS: 1023;
18:59:57 Sync: +DMR   slot1  [slot2] | Color Code=07 | CSBK
 C_ALOHA_SYS_PARMS: Small; Net ID: 1; Site ID: 3; SYS: 1023; Capacity Max -RAS 
18:59:57 Sync: +DMR  [slot1]  slot2  | Color Code=07 | CSBK
 C_ALOHA_SYS_PARMS: Small; Net ID: 1; Site ID: 3; SYS: 1023; -RAS 
18:59:57 Sync: +DMR   slot1  [slot2] | Color Code=07 | CSBK
 C_ALOHA_SYS_PARMS: Small; Net ID: 1; Site ID: 3; SYS: 1023; Capacity Max -RAS 
18:59:57 Sync: +DMR  [slot1]  slot2  | Color Code=07 | CSBK
 Announcements (C_BCAST) Adjacent Site Information (Adjacent_Site)
 Small; Net ID: 1; Site ID: 1; SYS: 1021; Online; CC Pri: 0; AC Pri: 0; LPCN: 1; -RAS 
 SLC_C_SYS_PARMS: Small; Net ID: 1; Site ID: 3; Reg Req: 1; SYS: 1023;

```

**Comment by firefighter76** [comment] 2024-01-03 18:38
Thank you for the explanation. 

The channel(s) I am receiving only transmits during communication and not constantly. So the -T switch doesn't help me.

I am very satisfied with the current solution.

**Comment by lwvmobile** [comment] 2024-01-03 19:01
Okay, well, if you are happy with the solution, then I'll go ahead and close this issue then.

**Closed as completed by lwvmobile** 2024-01-03 19:01 UTC

**Comment by lwvmobile** [comment] 2024-02-05 16:33
Just FYI on this, the recent commits I've made to the audio_work branch have incorporated this fixes found in any patches I've issues here for you, so if you do a pull on the most recent version, you won't need to apply the previous patch anymore.

**Comment by firefighter76** [comment] 2024-02-05 16:59
Thank you for the information.
